In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from sbe_vallib import BinaryValidation, BinaryScorer, BinarySampler

In [11]:
from sklearn.metrics import recall_score, f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np


def recall_at_10(true, preds):
    return recall_score(true, preds)

def custom_test(sampler, scorer):
    pass
    

X, y = make_classification(n_samples=1000, n_classes=2,
                               n_features=5, n_informative=3, n_redundant=0,
                               random_state=0)

# X = pd.DataFrame(X)
# y = pd.Series(y)

X_train, X_test,  y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y)

model = LogisticRegression().fit(X_train, y_train)


sampler = BinarySampler(train={'X': X_train, 'y_true': y_train, 'y_pred': model.predict_proba(X_train)},
                        oos = {'X': X_test, 'y_true': y_test, 'y_pred': model.predict_proba(X_test)}, bootstrap=False)

sampler.source_state = False

In [12]:
sampler.set_seed(17)
sampler.oos['X'][:5], sampler.oos['y_true'][:5], sampler.oos['y_pred'][:5], sampler.train['X'][:5], sampler.train['y_true'][:5], sampler.train['y_pred'][:5]

(array([[ 0.46143972, -1.69537569, -1.5182626 ,  0.82442795, -0.08336402],
        [-0.69246144,  2.23704828,  0.38583402,  0.00227872,  1.47992117],
        [-1.32491248,  0.07720959,  1.29029141,  0.45219062, -1.10471679],
        [-0.8766521 ,  1.61032686,  1.0745504 , -0.57405855, -0.16117053],
        [-1.84569454, -2.20248017,  1.70882929,  0.79824373,  0.36967722]]),
 array([0, 0, 0, 0, 1]),
 array([[0.89007993, 0.10992007],
        [0.70509165, 0.29490835],
        [0.34827256, 0.65172744],
        [0.48784982, 0.51215018],
        [0.14806622, 0.85193378]]),
 array([[ 0.57940749, -1.15709265, -0.65231463,  0.96757756,  0.85335123],
        [ 0.73363465,  3.00893782, -0.04292515, -0.27560993, -0.87936897],
        [-0.94300875,  0.949227  ,  0.53087666,  1.61447824,  0.54396227],
        [ 1.70654605, -0.15092923,  1.22477658, -1.37527906,  0.85749959],
        [ 0.30151611,  0.3975208 ,  2.75245527,  0.60540001, -0.60815928]]),
 array([0, 0, 0, 1, 1]),
 array([[0.71690493, 0.2

In [6]:
sampler = BinarySampler(train={'X': X_train, 'y_true': y_train, 'y_pred': model.predict_proba(X_train)},
                        oos = {'X': X_test, 'y_true': y_test, 'y_pred': model.predict_proba(X_test)}, bootstrap=True)
sampler.source_state = False
sampler.set_seed(10)
sampler.oos['X'][:5], sampler.oos['y_true'][:5], sampler.oos['y_pred'][:5], sampler.train['X'][:5], sampler.train['y_true'][:5], sampler.train['y_pred'][:5]

(array([[[ 2.33430351,  0.38273635, -0.12588233,  1.88957625,
          -0.66384185],
         [-1.73958053, -0.43645606,  1.27700304, -0.01665359,
          -0.29144691],
         [-0.09291869, -1.41670321,  2.39070834,  0.13449038,
           0.16464823],
         ...,
         [-0.53051614,  3.49799885,  0.88001123,  0.92378365,
           1.62205746],
         [ 0.64171797,  0.44712849, -0.7812042 , -0.49433701,
          -1.51270351],
         [ 0.70908585,  4.27660871, -0.16326807, -0.5274204 ,
          -1.59466283]]]),
 array([1, 1, 1, 1, 0]),
 array([[0.16169078, 0.83830922],
        [0.41276071, 0.58723929],
        [0.25701003, 0.74298997],
        [0.4154409 , 0.5845591 ],
        [0.77705339, 0.22294661]]),
 array([[-0.11693823, -1.56520668,  2.34834444,  0.97938353, -0.64896087],
        [-0.1420048 , -0.77715488,  1.57503639,  0.14245346, -1.42557847],
        [-0.34398586,  1.9920793 ,  0.42360526, -0.21832428, -0.81040176],
        [ 1.00294896, -0.66963678, -1.0514644

In [8]:
sampler = BinarySampler(train={'X': X_train, 'y_true': y_train, 'y_pred': model.predict_proba(X_train)},
                        oos = {'X': X_test, 'y_true': y_test, 'y_pred': model.predict_proba(X_test)}, bootstrap=False)
sampler.oos['X'][:5], sampler.oos['y_true'][:5], sampler.oos['y_pred'][:5], sampler.train['X'][:5], sampler.train['y_true'][:5], sampler.train['y_pred'][:5]

(array([[ 2.33430351,  0.38273635, -0.12588233,  1.88957625, -0.66384185],
        [-1.73958053, -0.43645606,  1.27700304, -0.01665359, -0.29144691],
        [-0.09291869, -1.41670321,  2.39070834,  0.13449038,  0.16464823],
        [ 0.78980481,  0.61461687,  1.19314586,  1.1571356 ,  0.04564895],
        [-2.69250435, -2.4062265 ,  1.14381774,  1.76774978,  1.67422915]]),
 array([0, 0, 1, 1, 1]),
 array([[0.52920199, 0.47079801],
        [0.31548146, 0.68451854],
        [0.03259623, 0.96740377],
        [0.22446524, 0.77553476],
        [0.24936442, 0.75063558]]),
 array([[-0.11693823, -1.56520668,  2.34834444,  0.97938353, -0.64896087],
        [-0.1420048 , -0.77715488,  1.57503639,  0.14245346, -1.42557847],
        [-0.34398586,  1.9920793 ,  0.42360526, -0.21832428, -0.81040176],
        [ 1.00294896, -0.66963678, -1.05146441, -0.12195011, -0.17421057],
        [ 2.51030858, -3.00694364, -1.04472174, -0.57153336,  1.48598004]]),
 array([1, 1, 0, 0, 0]),
 array([[0.03156631, 0.9

In [15]:
sampler_boot = BinarySampler(train={'X': X_train, 'y_true': y_train, 'y_pred': model.predict_proba(X_train)},
                        oos = {'X': X_test, 'y_true': y_test, 'y_pred': model.predict_proba(X_test)}, bootstrap=True)
sampler_no_boot = BinarySampler(train={'X': X_train, 'y_true': y_train, 'y_pred': model.predict_proba(X_train)},
                        oos = {'X': X_test, 'y_true': y_test, 'y_pred': model.predict_proba(X_test)}, bootstrap=True)

[np.array_equal(sampler_boot.oos['X'][:5], sampler_no_boot.oos['X'][:5]),
 np.array_equal(sampler_boot.oos['y_true'][:5], sampler_no_boot.oos['y_true'][:5]), 
 np.array_equal(sampler_boot.oos['y_pred'][:5],sampler_boot.oos['y_pred'][:5]),
 np.array_equal(sampler_boot.train['X'][:5],sampler_boot.train['X'][:5]),
 np.array_equal(sampler_boot.train['y_true'][:5],sampler_boot.train['y_true'][:5]),
 np.array_equal(sampler_boot.train['y_pred'][:5], sampler_boot.train['y_pred'][:5])]

[True, True, True, True, True, True]